### ISSUE TITLE
Function `find_too_close()` never used

### ISSUE THREAD

**Issue by JuanCab** [feder-observatory/stellarphot#105]
Function `find_too_close(star_locs, aperture_rad, pixel_scale=0.563)` in `photometry.py` doesn't appear to be called from anywhere in the stellarphot package.  Purge or do we need to use it!

**Comment by mwcraig** [comment]
Huh, weird. I thought that was used in either photometry or in the comparison star viewer stuff to avoid comparison stars that were too close together.

**Comment by JuanCab** [comment]
I reworked find_too_close() to work with either sky or x/y positions and it is available as an option in the single_image_photometry() function introduced in PR #141.
