### ISSUE TITLE
Is `plot_many_factors` actually used anywhere, seems incomplete?

### ISSUE THREAD

**Issue by JuanCab** [feder-observatory/stellarphot#128]
The `plot_many_factors` function in `visualization/transit_plots.py` doesn't seem to actually do anything useful (it makes some calculations, but the data is NOT kept before it exits.  Furthermore, the code doesn't seem to be used anywhere.  Purge it?

**Comment by mwcraig** [comment]
I think this was an attempt to move a bunch of code out of photometry notebook 06 and into an importable file. Looks like that was never completed, though...
