### ISSUE TITLE
Revisit a couple photometry issues

### ISSUE THREAD

**Issue by mwcraig** [feder-observatory/stellarphot#144]
I'm capturing a couple of things from #141 for further discussion so that that PR isn't held up:

+ Whet ra/dec or x/y wins in photometry if both are present https://github.com/feder-observatory/stellarphot/pull/141/files#r1277636446
+ Using attributes in one of the tests: https://github.com/feder-observatory/stellarphot/pull/141/files#r1278585231

**Comment by JuanCab** [comment]
I think issue #1 (ra/dec vs x/y) has now been adequately handled.  What would you like checked about the attributes, their creation?

**Comment by mwcraig** [comment]
I agree the first one is resolved. I'll take a look at the second one again once multiple_aperture_photometry is in, since I know the classes were re-worked a bit.

**Comment by mwcraig** [comment]
Closing, since I think this has been done....
