### ISSUE TITLE
Logging in the  photometry functions

### ISSUE THREAD

**Issue by mwcraig** [feder-observatory/stellarphot#148]
The new photometry functions have realy detailed progress output. It would be nice if

- [ ] There was an opt-in or opt-out mechanism (e.g. a `verbose` argument)
- [x] Consider using python logging instead of prints for the messaging

**Comment by JuanCab** [comment]
Just noting (based on our meat-space discussion) that:

1. We should make the log file name an argument of `single_image_photometry` and `multi_image_photometry`.  It should default to 'appending' to any existing log file and not nuking it.
2. We should raise Warnings (and log) any failures that force `single_image_photometry` to exit but still allow another image to be processed.
