### ISSUE TITLE
Change parameter in setup.cfg

### ISSUE THREAD

**Issue by mwcraig** [feder-observatory/stellarphot#156]
Got this warning while building stellarphot:

        ********************************************************************************
        The license_file parameter is deprecated, use license_files instead.

        By 2023-Oct-30, you need to update your project and remove deprecated calls
        or your builds will no longer be supported.

        See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
        ********************************************************************************

**Comment by JuanCab** [comment]
Where is the deprecated call?

**Comment by mwcraig** [comment]
I believe that [this line](https://github.com/feder-observatory/stellarphot/blob/main/setup.cfg#L9) should change to `license_files = licenses/LICENSE.rst` and the right hand side should (maybe?) be a list? Maybe tomorrow I'll run `hatch` to migrate to the newer packaging setup.

**Comment by mwcraig** [comment]
Fixed by #197
