### ISSUE TITLE
compute_fwhm fails if there are NaN values in the input

### ISSUE THREAD

**Issue by mwcraig** [feder-observatory/stellarphot#161]
It turns out that `compute_fwhm` fails if there are `NaN`s in the input data. Though there is an option to filter out infinite values (i.e. `np.inf`) but no way in astropy modeling to filter out `np.nan` though the documentation [explains how to do that in a note](https://docs.astropy.org/en/stable/modeling/fitting.html).

**Comment by JuanCab** [comment]
Is there a possibility you reverted the fix I applied in PR #145 to fix Issue #142 or is this a new error?

**Comment by mwcraig** [comment]
Have confirmed it is a real issue, think I found the cause. PR coming soon...
