### ISSUE TITLE
Notebook 02 problems

### ISSUE THREAD

**Issue by mwcraig** [feder-observatory/stellarphot#183]
- [ ] Add visual indication that aperture and variable files need to be saved or autosave them
- [x] Add settings for file names
- [x] Bring back some way to save TIC information?
- [ ] Offer a choice of source selection (maybe)

**Comment by Tanner728** [comment]
I am interested in working on this as well.

**Comment by mwcraig** [comment]
Which piece of it? The list of things I put up top is probably a little too chunky for one PR. Any one of them is probably a good size, though the last one is maybe a little trickier.

**Comment by Tanner728** [comment]
I could work on either of the first two. Which do you think is more important to have done?

**Comment by Tanner728** [comment]
I was thinking of how we could do this and was wondering where the function that puts the x's on stars or removes them when we shift click on stars is located? I have been looking through comparison functions but have not found it. Was thinking that we could autosave the files whenever a star is excluded or included in the lists.

**Comment by Tanner728** [comment]
So I was looking through the code and my first thought was to have the variables file save each time a star is removed or added back into the list of variables to be used. I think it would be something to call the `_save_variables_to_file` function added into this section of code in the `if not elims`and the corresponding `else` segment. 
```python
with outputwidget:
            index, d2d, d3d = out_skycoord.match_to_catalog_sky(all_table["coord"])
            if d2d < 10 * u.arcsec:
                mouse = all_table["coord"][index].separation(all_table["coord"])
                rat = mouse < 1 * u.arcsec
                elims = [
                    name
                    for name in all_table["marker name"][rat]
                    if name.startswith("elim")
                ]
                if not elims:
                    imagewidget.add_markers(
                        all_table[rat],
                        skycoord_colname="coord",
                        use_skycoord=True,
                        marker_name=f"elim{imagewidget.next_elim}",
                    )
                else:
                    for elim in elims:
                        try:
                            imagewidget.remove_markers_by_name(marker_name=elim)
                        except AttributeError:
                            imagewidget.remove_markers(marker_name=elim)
```

**Comment by mwcraig** [comment]
Interesting idea; I think you would need to call the function you are thinking about whenever an event happens that might change the list. I think there are only two:

- User clicks on a star (though that might only affect comparison stars, don't recall)
- Image is changed

**Comment by Tanner728** [comment]
I think from looking at the code selecting and deselecting a star affects the aperture file as well. For checking if a file changed would you say that seeing if the file name changed is the easiest approach?

**Comment by Tanner728** [comment]
I think from looking at the code selecting and deselecting a star affects the aperture file as well. For checking if a file changed would you say that seeing if the file name changed is the easiest approach?

**Comment by mwcraig** [comment]
> For checking if a file changed would you say that seeing if the file name changed 

Do you mean if there were changes made to the file outside the notebook?

**Comment by Tanner728** [comment]
Looking back I wasnt very clear with that statement. But to detect that the image has changed would it be quickest to look at the file name of the image?

**Comment by Tanner728** [comment]
I did have an idea on how to have an indicator that the aperture and variables files need to be saved and that would be to use the `valid` widget from ipywidgets and have the state be updated each time `wrap` is called or the file name changes as the file selection is handled by another class. Overall I think both approaches are fairly similar but I have not yet figured out how to make either of them work. Do you have a preference on how we do this, autosave or save indicator?

**Comment by Tanner728** [comment]
So I am trying some stuff out and ran into an error with notebook 2 that appears to not be related to any changes I have made. I stashed my changes and went back to the original notebook 2 and encountered the same error. It appears when I try to load in an image, I just grabbed one of our images from 2022-03-09. Any idea what is happening. It seems to trace back to the file chooser and fits opener.

![image](https://github.com/feder-observatory/stellarphot/assets/90003838/edcac2f9-e4c3-457b-97f1-64b1d3b9a8c8)

**Comment by Tanner728** [comment]
rebuilt my environment on my mini pc and encountered a new error. The error occurred when I tried loading an image in the notebook and it resulted in this.

File [c:\Users\tweye\miniforge3\envs\stellarphot-dev\Lib\site-packages\astroquery\utils\commons.py:249](file:///C:/Users/tweye/miniforge3/envs/stellarphot-dev/Lib/site-packages/astroquery/utils/commons.py:249), in TableList.__getitem__(self, key)
    [246](file:///C:/Users/tweye/miniforge3/envs/stellarphot-dev/Lib/site-packages/astroquery/utils/commons.py:246) def __getitem__(self, key):
    [247](file:///C:/Users/tweye/miniforge3/envs/stellarphot-dev/Lib/site-packages/astroquery/utils/commons.py:247)     if isinstance(key, int):
    [248](file:///C:/Users/tweye/miniforge3/envs/stellarphot-dev/Lib/site-packages/astroquery/utils/commons.py:248)         # get the value in the (key,value) pair
--> [249](file:///C:/Users/tweye/miniforge3/envs/stellarphot-dev/Lib/site-packages/astroquery/utils/commons.py:249)         return super(TableList, self).__getitem__(key)
    [250](file:///C:/Users/tweye/miniforge3/envs/stellarphot-dev/Lib/site-packages/astroquery/utils/commons.py:250)     elif key in self._dict:
    [251](file:///C:/Users/tweye/miniforge3/envs/stellarphot-dev/Lib/site-packages/astroquery/utils/commons.py:251)         return self._dict[key]

IndexError: list index out of range

**Comment by Tanner728** [comment]
To setup my environments I followed those instructions you linked above and have been synching my branches with the upstream repo fairly commonly. Just synched them again and got the same error.

**Comment by mwcraig** [comment]
Can you send the output of `mamba list` for that environment when you get a chance?

**Comment by Tanner728** [comment]
I can do that when I head in for lunch today.

**Comment by mwcraig** [comment]
What image is it?

**Comment by Tanner728** [comment]
Tried a new image and it worked fine must have been the image. The image that was not working was `TIC_81247877.01-S001-R012-C001-rp.fit`

**Comment by Tanner728** [comment]
To autosave the files would we be able to observe if the `elims` list changes and save the files whenever that does happen? 
The elims list is in this bit of code from the `wrap` function. 

```python

with outputwidget:
            index, d2d, d3d = out_skycoord.match_to_catalog_sky(all_table["coord"])
            if d2d < 10 * u.arcsec:
                mouse = all_table["coord"][index].separation(all_table["coord"])
                rat = mouse < 1 * u.arcsec
                elims = [
                    name
                    for name in all_table["marker name"][rat]
                    if name.startswith("elim")
                ]
                if not elims:
                    imagewidget.add_markers(
                        all_table[rat],
                        skycoord_colname="coord",
                        use_skycoord=True,
                        marker_name=f"elim{imagewidget.next_elim}",
                    )
                else:
                    for elim in elims:
                        try:
                            imagewidget.remove_markers_by_name(marker_name=elim)
                        except AttributeError:
                            imagewidget.remove_markers(marker_name=elim)

            else:
                print("sorry try again")
                imagewidget._viewer.onscreen_message("Click closer to a star")
    return cb

```

**Comment by mwcraig** [comment]
There are a couple of prerequisites to observing something (at least in the widget-y sense -- one could just call some function when elims is updated, I suppose):

- the thing needs to be a traitlet (a specific type of property of an iobject) 
- you can't monitor for changes in list contents but you can watch for when a list traitlet is set to a new list

For elims specifically it might make sense to just call a function; in the future finding a way to monitor markers on the image.

The other event which should prompt a need to resave is if the file selected changes. That will be much easier when #247 is fixed. Do you want me to do that today?

**Comment by Tanner728** [comment]
I will be skiing and doing homework for most of the day but will have time to work on it tomorrow. If you have time to get to it then that is great but there is no rush. I will be back on campus starting Sunday.
