### ISSUE TITLE
Make an object to represent an exoplanet

### ISSUE THREAD

**Issue by mwcraig** [feder-observatory/stellarphot#186]
Among other things, this should have:

- Epoch
- Period
- Identifier (TIC ID or name)
- Coordinates
- Depth, if known
- duration, if known
- ???

**Comment by Tanner728** [comment]
I would be interested in working on this.

**Comment by mwcraig** [comment]
Excellent! I'm thinking this will be a pydantic-based class like the settings are.

**Comment by Tanner728** [comment]
for each of these attributes i believe we had originally wanted them to be the following things

- Epoch: astropy time object
- Period: astropy time object?
- Identifier (TIC ID or name) string?
- Coordinates: Skycoord
- Depth, if known: float
- duration, if known: astropy time object?

I think this is what we had said...

**Comment by mwcraig** [comment]
@Tanner728  You should probably start taking better notes 😀 

In any event, I think they are:

- epoch: astropy time object
- period: float with unit of time (i.e. Quantity)
- identifier: string
- coordinates: SkyCoord
- depth, if known: float (fine for now -- later may want to add units since this can be ppt, ppm, %, or mmag typically but these are weird "units" since technically they are not units)
- duration, if known:  float with unit of time (i.e. Quantity)

**Comment by Tanner728** [comment]
I have found the parts per million unit that we spoke about yesterday and have added units to the other values that would need them in the test but for some reason my exoplanet test is not being picked up by the tester. I have tried restarting VS code. To use the parts per million unit I had to import the cds module of astropy.units and enable it.

```python
from pydantic import ValidationError
import pytest

from stellarphot.settings.models import ApertureSettings
from stellarphot.settings.models import Exoplanet

from astropy.coordinates import SkyCoord
import astropy.units as u
from astropy.units import cds
cds.enable()
```




```python

DEFAULT_EXOPLANET_SETTINGS = dict(epoch=0*u.cds.JD, period=0*u.min, identifier='', coordinate=SkyCoord(ra='00:00:00.00', dec='+00:00:00.0', frame='icrs', unit=('hour', 'degree')), depth=0*u.cds.ppm, duration=0*u.min)


def test_create_exoplanet_correctly():
    planet = Exoplanet(**DEFAULT_EXOPLANET_SETTINGS)
    assert planet.epoch == DEFAULT_EXOPLANET_SETTINGS["epoch"]
    assert planet.period == DEFAULT_EXOPLANET_SETTINGS["period"]
    assert planet.identifier == DEFAULT_EXOPLANET_SETTINGS["identifier"]
    assert planet.coordinate == DEFAULT_EXOPLANET_SETTINGS["coordinate"]
    assert planet.depth == DEFAULT_EXOPLANET_SETTINGS["depth"]
    assert planet.duration == DEFAULT_EXOPLANET_SETTINGS["duration"]
```

**Comment by Tanner728** [comment]
Ok its being weird. I reformatted the code so I didnt have to scroll over in the default setttings and it doesnt like have all zeros in the sky coords
``` python
DEFAULT_EXOPLANET_SETTINGS = dict(epoch=0*u.cds.JD,
                                  period=0*u.min,
                                  identifier='',
                                  coordinate=SkyCoord(ra='01:01:01.00', dec='+02:20:20.0', frame='icrs', unit=('hour', 'degree')), 
                                  depth=0*u.cds.ppm,
                                  duration=0*u.min)


def test_create_exoplanet_correctly():
    planet = Exoplanet(**DEFAULT_EXOPLANET_SETTINGS)
    assert planet.epoch == DEFAULT_EXOPLANET_SETTINGS["epoch"]
    assert planet.period == DEFAULT_EXOPLANET_SETTINGS["period"]
    assert planet.identifier == DEFAULT_EXOPLANET_SETTINGS["identifier"]
    assert planet.coordinate == DEFAULT_EXOPLANET_SETTINGS["coordinate"]
    assert planet.depth == DEFAULT_EXOPLANET_SETTINGS["depth"]
    assert planet.duration == DEFAULT_EXOPLANET_SETTINGS["duration"]
```

**Comment by mwcraig** [comment]
Which zeroes doesn't it like?

**Comment by Tanner728** [comment]
the ones in the sky coordinate for the default settings.

**Comment by mwcraig** [comment]
What do you get when you click "Show output" in the red box in the upper left? I'm not seeing an error when I try create a SkyCoord....

**Comment by mwcraig** [comment]
Ah, CDS is the issue....from the enable docstring:

```
Enable CDS units so they appear in results of
`~astropy.units.UnitBase.find_equivalent_units` and
`~astropy.units.UnitBase.compose`.  This will disable
all of the "default" `astropy.units` units, since there
are some namespace clashes between the two.
```

I would drop the ppm for now and not enable CDS.

**Comment by Tanner728** [comment]
Sounds good.
