### ISSUE TITLE
Outline documentation 

### ISSUE THREAD

**Issue by mwcraig** [feder-observatory/stellarphot#191]
- [ ] Write outline
- [ ] Open issues for specific tasks

**Comment by Tanner728** [comment]
Is this something that I would be able to help with?

**Comment by mwcraig** [comment]
This is one I probably need to do....

**Comment by Tanner728** [comment]
That was what I figured. Seems a bit much for us mere students.

**Comment by Tanner728** [comment]
I can work on any of the linting issues so feel free to assign me whatever you want. Work at Detroit Mountain (hill) got canceled due to a lack of snow.

**Comment by mwcraig** [comment]
> That was what I figured. Seems a bit much for us mere students.

Not that as much as that it hasn't been clearly laid out how this is supposed to work :)

**Comment by mwcraig** [comment]
> I can work on any of the linting issues so feel free to assign me whatever you want. Work at Detroit Mountain (hill) got canceled due to a lack of snow.

Can you please comment on the individual issues you want to work on?
