### ISSUE TITLE
Add BJD calculation option to photometry_on_directory

### ISSUE THREAD

**Issue by mwcraig** [feder-observatory/stellarphot#22]
Maybe by adding a target coordinate parameter or something?

**Comment by mwcraig** [comment]
THis has maybe been done???

**Comment by mwcraig** [comment]
Though if it has it is probably hard-wired to Feder Observatory

**Comment by mwcraig** [comment]
NEXT STEPS: Figure out what the current state of affairs is. Looking at the code for `add_to_photometry_table` would be the place to start, I think.

**Comment by JuanCab** [comment]
Should be addressed by the new PhotometryData class for storing data.
