### ISSUE TITLE
Fix linting issues in photometry

### ISSUE THREAD

**Issue by mwcraig** [feder-observatory/stellarphot#222]
For all of [these issues](https://github.com/feder-observatory/stellarphot/issues?q=is%3Aopen+is%3Aissue+label%3Alinting), first delete the appropriate line in `pyproject.toml` that excludes the subpackage from checks. for `photometry` you would delete [this line](https://github.com/feder-observatory/stellarphot/blob/main/pyproject.toml#L123):

```toml
"stellarphot/photometry/*" = ["F"]
```

After that, run `ruff` either with `tox -e lint` or `ruff .`. The errors you get should be the ones -- fix them! If it is an unused function argument make sure to search the project for calls to that function to update the arguments there too.

- [ ] stellarphot/photometry/tests/test_photometry.py:526:9: F841 Local variable `expected_deviation` is assigned to but never used
- [ ] stellarphot/photometry/tests/test_photometry.py:578:13: F841 Local variable `phot_data` is assigned to but never used
- [ ] stellarphot/photometry/tests/test_photometry.py:637:13: F841 Local variable `phot_data` is assigned to but never used

**Comment by Tanner728** [comment]
I would also like to work on this one.

**Comment by mwcraig** [comment]
My best guess is that in these cases the lines with the unused variables can just be deleted...don't know for sure.

**Comment by mwcraig** [comment]
This needs to wait until #236 is merged, since that PR adds some more photometry functions
