### ISSUE TITLE
Fix linting issues in tests

### ISSUE THREAD

**Issue by mwcraig** [feder-observatory/stellarphot#224]
For all of [these issues](https://github.com/feder-observatory/stellarphot/issues?q=is%3Aopen+is%3Aissue+label%3Alinting), first delete the appropriate line in `pyproject.toml` that excludes the subpackage from checks. for `tests` you would delete [this line](https://github.com/feder-observatory/stellarphot/blob/main/pyproject.toml#L125):

```toml
"stellarphot/tests/*" = ["F"]
```

After that, run `ruff` either with `tox -e lint` or `ruff .`. The errors you get should be the ones -- fix them! If it is an unused function argument make sure to search the project for calls to that function to update the arguments there too.

- [ ] stellarphot/tests/test_core.py:72:9: F841 Local variable `c` is assigned to but never used
- [ ] stellarphot/tests/test_core.py:292:9: F841 Local variable `test_base` is assigned to but never used
- [ ] stellarphot/tests/test_core.py:303:9: F841 Local variable `test_base` is assigned to but never used
- [ ] stellarphot/tests/test_core.py:316:9: F841 Local variable `test_base3` is assigned to but never used
- [ ] stellarphot/tests/test_core.py:606:9: F841 Local variable `phot_data` is assigned to but never used
- [ ] stellarphot/tests/test_core.py:616:9: F841 Local variable `phot_data` is assigned to but never used
- [ ] stellarphot/tests/test_core.py:656:9: F841 Local variable `catalog_dat` is assigned to but never used
- [ ] stellarphot/tests/test_core.py:725:9: F841 Local variable `catalog_dat2` is assigned to but never used
- [ ] stellarphot/tests/test_core.py:979:9: F841 Local variable `sl_test` is assigned to but never used
- [ ] stellarphot/tests/test_core.py:989:9: F841 Local variable `sl_test2` is assigned to but never used

**Comment by Tanner728** [comment]
I am interested in helping with this. I have extra time this week as Detroit mountain is closed today due to rain.

**Comment by mwcraig** [comment]
I'm not sure why this closed -- the pull request you opened was to *your* fork of stellarphot instead of to this copy. 

If you go here: https://github.com/feder-observatory/stellarphot/compare

and then select your fork and branch:

<img width="1260" alt="Compare_·_feder-observatory_stellarphot" src="https://github.com/feder-observatory/stellarphot/assets/1147167/67145940-81e6-4376-b923-8e46e9793dad">

**Comment by Tanner728** [comment]
That's what I thought I had done but was confused why it closed the issue.
