### ISSUE TITLE
Fix linting issues in transit_fitting

### ISSUE THREAD

**Issue by mwcraig** [feder-observatory/stellarphot#225]
For all of [these issues](https://github.com/feder-observatory/stellarphot/issues?q=is%3Aopen+is%3Aissue+label%3Alinting), first delete the appropriate line in `pyproject.toml` that excludes the subpackage from checks. for `transit_fitting` you would delete [this line](https://github.com/feder-observatory/stellarphot/blob/main/pyproject.toml#L126):

```toml
"stellarphot/transit_fitting/*" = ["ARG"]
```

After that, run `ruff` either with `tox -e lint` or `ruff .`. The errors you get should be the ones -- fix them! If it is an unused function argument make sure to search the project for calls to that function to update the arguments there too.

- [ ] stellarphot/transit_fitting/core.py:144:24: ARG002 Unused method argument: `batman_params`
- [ ] stellarphot/transit_fitting/core.py:336:13: ARG001 Unused function argument: `time`
- [ ] stellarphot/transit_fitting/gui.py:77:31: ARG002 Unused method argument: `change`
- [ ] stellarphot/transit_fitting/gui.py:136:46: ARG001 Unused function argument: `value_widget`
- [ ] stellarphot/transit_fitting/gui.py:390:24: ARG001 Unused function argument: `change`

**Comment by Tanner728** [comment]
I can work on this one.

**Comment by Tanner728** [comment]
I was just starting to look at this issue and wanted to confirm the issues. Here is what I get when running Tox and ruff on the file. 
![image](https://github.com/feder-observatory/stellarphot/assets/90003838/2a61e1af-afb5-46b9-bf3a-720dbc8a4b26)

**Comment by mwcraig** [comment]
I just did a fix in #244 -- turns out this one was a little subtle.

To answer your questions, don't worry about the skipped tests. 

For the linting fixes (which are, I think, either done or assigned) you should get errors when you first run the lint (or ruff) -- those are the things that need to get fixed.

**Comment by Tanner728** [comment]
Ok sounds good. I did not see all of those fixes in #244 but that is good to know.
