### ISSUE TITLE
Maybe make `Camera` and `Observatory` table attributes

### ISSUE THREAD

**Issue by mwcraig** [feder-observatory/stellarphot#232]
The `PhotometryTable` code has this comment:

```python
# Add the TableAttributes directly to meta (and adding attribute
# functions below) since using TableAttributes results in a
# inability to access the values to due a
# AttributeError: 'TableAttribute' object has no attribute 'name'
```

I was able to work out today how to make things like `Camera` round trip to `ECSV` -- should we make these attributes so that the objects don't have to be unpacked into `meta` the way they are [here](https://github.com/feder-observatory/stellarphot/blob/main/stellarphot/core.py#L624)?

**Comment by mwcraig** [comment]
@JuanCab

**Comment by JuanCab** [comment]
I would need to know more about *how* this is going to be done.  I didn't like the meta solution because we had to MANUALLY set all the attributes to be packed up... does your approach just automatically handle things?  What's the new approach?

**Comment by mwcraig** [comment]
Take a look at #233 -- when trying to add a test I came across an unrelated error, opening separate issue for that....
