### ISSUE TITLE
Update code to pydantic 2

### ISSUE THREAD

**Issue by mwcraig** [feder-observatory/stellarphot#262]
Now that ipyautoui has updated to pydantic 2, we can too. A few things are entailed here:

+ Change requirements in `pyproject.toml` to bump the minimum version for ipyautoui and pydantic
+ Change any v1 code that is deprecated in v2 of pydantic
+ Maybe change how we handle custom types derived from astropy -- it looks like there are more options for integrating non-pydantic-types with pydantic without defining new classes.

**Comment by JuanCab** [comment]
Definitely an issue since `pyautoui` has now migrated to pydantic 2.
