### ISSUE TITLE
Installation Instructions Need Updating

### ISSUE THREAD

**Issue by JuanCab** [feder-observatory/stellarphot#333]
I am pretty sure the installation instructions on the front page of the GitHub repo need updating as I don't think we need `astronbs` any more.  @mwcraig I can tackle this if you like, just assign it to me.  Any update should likely include instructions for installing with `pip` and `conda`.

**Comment by JuanCab** [comment]
@mwcraig  OK, I have experimented with the installation instructions (I realized that `astronbs` allows you to have specific Jupyter notebooks available in Jupyter by default, so it is necessary).

I do think there are two issues which should be addressed in the `README.md` installation instructions:

1. Python 3.9 is deprecated, I *thought* Python 3.11 was the minimum for the code based on a discussion last summer.  Should we update this?  Given we are targeting version 2.0 for this summer and 3.10 is scheduled for deprecation this fall, it seems prudent to push the requirement to 3.11.
2. Should we suggest the creation of a separate environment (by providing a `conda` `environment.yml` file and by describing the creation of a `venv` directory).  I like conda's environment set up a lot more than the `venv` approach, but in general I do like the idea of specific environments for doing specific work.  This would not necessarily replace the current instructions completely, but would require use to provide a `environment.yml` file for conda environment and revise the instructions to mention environments as an option.

**Comment by mwcraig** [comment]
I'm fine with bumping the minimum python version up to 3.11.

For 2, I'd be inclined to stay away from specifying an environment file. As long as we provide a feedstock for it then you can create an environment with `conda install stellarphot` that will have the necessary dependencies. 

For development I think `pip install -e .[test]` (in an environment created however you like) is the way to go.

**Comment by JuanCab** [comment]
I think the merging of PR #356 addressed this, closing.
