### ISSUE TITLE
Update Contributors even more

### ISSUE THREAD

**Issue by JuanCab** [feder-observatory/stellarphot#353]
@mwcraig I realized we list quite a few people [here](https://zenodo.org/records/10679636) as contributors that are not listed on this page.  Should we add them to the list of contributors?  The people we would need to add are:

- Thomas Robitaille (@astrofrog)
- Brigitta Sipőcz (@bsipocz)
- Erik Tollerud (@eteq)
- Michael Droettboom (@mdboom)
- Larry Bradley (@larrybradley)
- E. M. Bray (@embray)
- Christoph Deil (@cdeil)
- Adrian Price-Whelan (@adrn)
- Adam Ginsburg (@keflavich)
- Kyle Barbary (@kbarbary)
- Isobel Snellenberger (@isobelsnellenberger)
- Stefan Nelson (@stefannelson)
- Wolfgang Kerzendorf (@wkerzendorf)
- Nathan Walker (@walkerna22)
- Hans Moritz Günther (@hamogu)
- Víctor Zabalza (@zblz)
- Steve Crawford (@crawfordsm)
- Jane Glanzer (@janeglanzer)

I didn't know how you might want to list their contributions, so I didn't just want to add them.  The [categories for each person's all-contributor's contributions are listed here](https://allcontributors.org/docs/en/emoji-key).

**Comment by mwcraig** [comment]
I can go through these next week and try to sort them out. Some of them made code contributions when it was glowing-waffles but I think some are folks who worked on the package template at something point....

**Comment by JuanCab** [comment]
> @JuanCab -- could we delay this to a little later? I'd like to get a 2.0 alpha release out this week and this seems like something that could wait a bit....

I think it is fine to wait for the alpha, but certainly by any wider beta release we should give credit where credit is due!

**Comment by mwcraig** [comment]
@all-contributors please add @isobelsnellenberger for code

**Comment by mwcraig** [comment]
@all-contributors please add @stefannelson for code and userTesting

**Comment by mwcraig** [comment]
@all-contributors please add @isobelsnellenberger for user testing

**Comment by mwcraig** [comment]
@all-contributors please add @walkerna22 for code and user testing

**Comment by mwcraig** [comment]
@all-contributors please add @janeglanzer for code and user testing

**Comment by mwcraig** [comment]
@JuanCab -- I've added everyone from this list who made code contributions to anything except the old astropy package template. 

I'm inclined not to add the rest of the folks...little of that code is still around.

If you are ok with that, can you please close this?

**Comment by JuanCab** [comment]
Sounds good, closing this issue.
