### ISSUE TITLE
Codecov report is way off

### ISSUE THREAD

**Issue by mwcraig** [feder-observatory/stellarphot#396]
The codecov report is way off because it is including test and __init__ files in the count of source lines. When I run coverage locally it gets the correct coverage number (about 83%). 

@JuanCab -- do you have any time to look into this today?

**Comment by JuanCab** [comment]
I can look at this this afternoon.

**Comment by mwcraig** [comment]
I think it is more important to get codecov working....if we can't in the next days or so we just won't worry about it.
