### ISSUE TITLE
Release 2.0.0-alpha

### ISSUE THREAD

**Issue by mwcraig** [feder-observatory/stellarphot#399]
This issue is intended to be closed when we do the alpha release.

Draft message to send to testers -- please send suggestions @JuanCab and @Tanner728 

Dear X,

Thank you for your interest in trying out stellarphot. We are ready for folks to start taking a look at the software and invite you to provide feedback.

## Who should try out this release

Please only try out this release if you are comfortable working at the command line in a terminal and with creating and removing python environments (instructions are provided for doing this). Later test releases will be easier to try out. We are primarily testing the JupyterLab interface in this release.

## What feedback we are are looking for

We do not need every tester to answer every question but these are the kinds of question we are trying to answer in this round of testing.

+ Do the installation instructions work for you?
+ Was the documentation adequate for you to create each of the four notebooks in the JupyterLab launcher?
+ Were you able to run each notebook? What difficulties did you encounter?
+ Were you able to perform photometry on the test images?
+ Were you able to perform photometry on your own images?

## How to provide feedback

We prefer it if you open an issue here: https://github.com/feder-observatory/stellarphot/issues/new/choose

Issues can be small (typos you notice) or large.

You can instead just reply to this email to provide feedback if you prefer.

## What to install/do

1. Please go to [this link](https://stellarphot.readthedocs.io/2.0.0.alpha0/#installation) and install stellarphot. We recommend using a dedicated environment for testing. You can remove the environment when you are done testing this version.
2. Once you have stellarphot installed, please launch JupyterLab and try running notebook 1 through 4 (this will make sense after you look at the docs). If possible, use a FITS image or two that you have. If you need some to test stellarphot then you can get a couple images from here: https://physics.mnstate.edu/matt.craig/sample-images.zip

**Comment by mwcraig** [comment]
@JuanCab @Tanner728 --can you please try follow the instructions above? If they work for you I will send out an email.

**Comment by Tanner728** [comment]
The instructions all worked but when I launched into jupyter lab there were no notebooks present in the launcher. 
![image](https://github.com/user-attachments/assets/a0601de7-55ac-40de-92fd-701e55d42e1d)

**Comment by mwcraig** [comment]
Thanks, working on fixing that. Turns out there are some pretty fundamental things I didn't understand about building wheels. I hope to be able to forget all of them soon...

**Comment by JuanCab** [comment]
> The instructions all worked but when I launched into jupyter lab there were no notebooks present in the launcher. !

I can confirm that I also am not seeing the icons for the notebooks.

**Comment by Tanner728** [comment]
> Thanks, working on fixing that. Turns out there are some pretty fundamental things I didn't understand about building wheels. I hope to be able to forget all of them soon...

Hopefully we dont have to reinvent the wheel to solve this...

**Comment by JuanCab** [comment]
> > Thanks, working on fixing that. Turns out there are some pretty fundamental things I didn't understand about building wheels. I hope to be able to forget all of them soon...
> 
> 
> 
> Hopefully we dont have to reinvent the wheel to solve this...

Quit distracting @mwcraig With your puns, he has to get 'round to solving this problem.

**Comment by Tanner728** [comment]
> > > Thanks, working on fixing that. Turns out there are some pretty fundamental things I didn't understand about building wheels. I hope to be able to forget all of them soon...
> > 
> > 
> > Hopefully we dont have to reinvent the wheel to solve this...
> 
> Quit distracting @mwcraig With your puns, he has to get 'round to solving this problem.

Knowing him, his solution will probably be pretty roundabout.

**Comment by mwcraig** [comment]
> Hopefully we dont have to reinvent the wheel to solve this...

+💯

 > when I launched into jupyter lab there were no notebooks present in the launcher.

@Tanner728 @JuanCab - I believe this is fixed in `2.0.0a1`, please give it a try

**Comment by Tanner728** [comment]
I will test this tonight

**Comment by mwcraig** [comment]
> I will test this tonight

Thanks for kicking the tires 🛞

**Comment by Tanner728** [comment]
The link listed above with the instructions is resulting in a 404 error. 
https://stellarphot.readthedocs.io/2.0.0.alpha0/#installation

**Comment by mwcraig** [comment]
Thanks, it should be https://stellarphot.readthedocs.io/2.0.0.alpha1/#installation

I might make it a more general link if I can....

**Comment by Tanner728** [comment]
![image](https://github.com/user-attachments/assets/9e3f5926-c0f9-414e-bd77-5652a17298e0)
can confirm notebooks are present now

**Comment by mwcraig** [comment]
Closing, since alpha has been out for a while.
