### ISSUE TITLE
BJD calculation is per star, not per frame

### ISSUE THREAD

**Issue by mwcraig** [feder-observatory/stellarphot#444]
I noticed yesterday that the BJD calculation, which is done in [`PhotometryData`](https://github.com/feder-observatory/stellarphot/blob/main/stellarphot/core.py#L260), has an issue.

In the past, `BJD_TDB` was calculated using the center of the frame as the RA/Dec. Now it is being calculated for each star individually in [`add_bjd_column`](https://github.com/feder-observatory/stellarphot/blob/main/stellarphot/core.py#L260), which results with each star in a single image having a slightly different BJD. 

While at some level that is maybe the correct behavior (or at least not incorrect behavior), since BJD does depend on RA and Dec, it is not usually what one wants. Instead, having a single BJD for each image is more useful.

I have not yet looked into how large a field of view one would need to have for there to be meaningful difference in BJD across the image, but I'm guessing it is tens of degrees.

@JuanCab -- what do you think about this? Maybe meet up to hash out how to handle it?

**Comment by JuanCab** [comment]
I seem to recall bringing this up when I added automatic determination of each BJD while processing observations.  I agree usually people settle on BJD in a field (especially given the small variations in BJD in a small field).  I imagine that outside of pulsar observations, getting the BJD specific to each target in the field is rarely scientifically usable.  I would be fine with settling on a mechanism for selecting a single BJD for the field.  I suspect BJD at the center of the field would be adquate.

If you want to hash this out in person, I am game.  I'll have more free time after this week ends. :)
